### ISSUE TITLE
请问使用有版本限制吗

### ISSUE THREAD

**Issue by redstarbury** [jrr997/antd-doc-vscode#5]
"我尝试使用安装了，不过 vscode 启动后没有能够安装，不知道如何可以触发这个效果，目前我的 vscode 版本是 1.85.1，目前看到是在 tsx 可以生效，但是 jsx 不能生效"
好吧，符合预期，看到注册的时候，没有注册 jsx 的文件

**Comment by jrr997** [comment]
jsx 无法使用是这个插件的 bug，目前已经修复了。你可以更新一下插件到1.0.0版本。
